---
- name: Add Nginx Repository
  become: True
  apt_repository: repo=ppa:nginx/stable state=present

- name: Install Nginx
  become: True
  apt: pkg=nginx state=installed update_cache=true
  notify:
    - Start Nginx

- name: Add H5BP Config
  become: True
  copy: src=h5bp dest=/etc/nginx owner=root group=root
  tags:
    - vhost

- name: Add Nginx Config
  become: True
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root
  tags:
    - vhost

- name: Add Nginx Mime Types
  become: True
  file: src=mime.types dest=/etc/nginx/mime.types owner=root group=root
  tags:
    - vhost

- name: Disable Default Site
  become: True
  file: dest=/etc/nginx/sites-enabled/default state=absent
  tags:
    - vhost

- name: Add Application Configuration
  become: True
  template: src={{ application_name }}.j2 dest/etc/nginx/sites-available/{{ application_name }}.conf owner=root group=root
  tags:
    - vhost
  notify:
    - Reload Nginx

- name: Enable Application Configuration
  become: True
  file: src=/etc/nginx/sites-available/{{ application_name }}.conf dest=/etc/nginx/sites-enabled/{{ application_name }}.conf state=link
  tags:
    - vhost
  notify:
    - Reload Nginx

...
