---
- hosts: all
  roles:
    - ubuntu_packages
    - vagrant
    # - ruby
    # - nodejs
    # - postgres
    # - imagemagick
    # - nginx
    # - php7
    # - aws-cli
    # - role: mysql
    #   become: True
  gather_facts: no
  pre_tasks:
    - raw: sudo apt install -y python

...
