---
- hosts: all
  roles:
    - ubuntu_packages
    - vagrant
    - ruby
    - customize_git
    - nodejs
    - postgres
    - imagemagick
    - nginx
    - php7
    - aws-cli
    - role: mysql
      become: True

...
