---
  # man aptitude for safe upgrade info
- name: Perform Safe Upgrade
  become: True
  apt: upgrade=safe update_cache=yes

- name: Installing packages
  become: True
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - curl
    - git
    - make
    - tree
    - htop
    - build-essential
    - python-software-properties
    - vim
    - libxslt-dev
    - libxml2-dev
    - libgmp-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
    - libyaml-dev
    - libfontconfig1
    - libncurses5-dev
    - unzip
    - wget
    - unattended-upgrades
    - ntp
  notify:
    - Start NTP

- name: Set locale to {{ locale }}
  locale_gen: name={{ locale }} state=present

- name: Add Periodic Configuration
  become: True
  copy: src=10periodic dest=/etc/apt/apt.conf.d/10periodic owner=root group=root

- name: Add Unattended Upgrade Configuration
  become: True
  copy: src=50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades owner=root group=root
  notify:
    - Restart Unattended Upgrades

...
