---

- name: Install Basic Packages
  become: True
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - curl
    - git
    - make
    - tree
    - htop
    - build-essential
    - software-properties-common
    - vim
    - libxslt-dev
    - libxml2-dev
    - libgmp-dev
    - zlib1g-dev
    - libssl-dev
    - libreadline6-dev
    - libyaml-dev
    - libfontconfig1
    - libncurses5-dev
    - unzip
    - wget

- name: Set locale to {{ locale }}
  locale_gen: name={{ locale }} state=present

...
